# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c695e011a6e97308f11f5d13204192c11c3a293fe01ae12620ec588d7034e1dabfdf0232e7fe1307882c255f8d0e0b2b1924cb7744a470139f3c6eee4bdf480

test:
  secret_key_base: 3f2db0abd1cb04354b6f489ec3677e1aa6ec95e6645e6c4b22c2d61c1bd845f1ae09488c654a7c59bdbc3c2a749998d166c8e4436a156267e876fc0736128b74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
